project:
  type: website
  output-dir: docs

website:
  title: "Choice Process Data Workshop"
  favicon: images/favicon.png
  search: false
  navbar:
    background: primary
    foreground: light
    search: false
    right:
      - text: "ESA World Meeting"
        href: "https://economicscience.org/"
  page-footer:
    left: |
      Fifth Workshop on Choice Process Data &copy; 2026
    center: |
      ESA World Meeting 2026
    right: |
      [Contact Organizers](mailto:krajbich@ucla.edu)

format:
  html:
    theme:
      - cosmo
      - styles/custom.scss
    css: styles/styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    code-copy: false
    code-tools: false
